### ISSUE TITLE
patch for "Error compiling fragment shader: /shaders/gbuffers_terrain.fsh"

### ISSUE THREAD

**Issue by plredmond** [Sildurs-shaders/sildurs-shaders.github.io#118]
**Sildurs Vibrant Shaders v1.281 Lite.zip**

I got this error when I turned on bumpmapping.
```
...
[11:54:13] [main/ERROR]: [Shaders] Error compiling fragment shader: /shaders/gbuffers_terrain.fsh
[11:54:13] [main/INFO]: [Shaders] File: 1 = /shaders/shaders.settings
[11:54:13] [main/INFO]: [Shaders] Shader info log: /shaders/gbuffers_terrain.fsh
0:46(1): error: #extension directive is not allowed in the middle of a shader
[11:54:13] [main/ERROR]: [Shaders] Error linking program: 287 (gbuffers_terrain)
[11:54:13] [main/INFO]: [Shaders] Info log: gbuffers_terrain
error: linking with uncompiled/unspecialized shader
[11:54:13] [main/ERROR]: OpenGL API ERROR: 3 (GL_INVALID_OPERATION in glUseProgram(program 287 not linked))
java.lang.Exception: Stack trace
	at org.lwjgl.opengl.ARBShaderObjects.glUseProgramObjectARB(Native Method) ~[lwjgl-opengl-3.2.2.jar:build 10]
	at net.optifine.shaders.Shaders.useProgram(Shaders.java:3391) [Shaders.class:?]
	at net.optifine.shaders.Shaders.setupProgram(Shaders.java:2692) [Shaders.class:?]
	at net.optifine.shaders.Shaders.init(Shaders.java:2364) [Shaders.class:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4113) [Shaders.class:?]
	at dzz.a(GameRenderer.java:949) [dzz.class:?]
	at dzz.a(GameRenderer.java:693) [dzz.class:?]
	at djz.e(SourceFile:1048) [djz.class:?]
	at djz.e(SourceFile:681) [djz.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:215) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_272]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_272]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_272]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_272]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
[11:54:13] [main/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: gbuffers_terrain, at: useProgram
[11:54:13] [main/ERROR]: [Shaders] [Shaders] Error: Invalid program "gbuffers_terrain"
[11:54:13] [main/INFO]: [CHAT] [Shaders] Error: Invalid program "gbuffers_terrain"
...
```
This patch fixed the error and seemed to enable bumpmapping for me.
```patch
diff -u -r lite_orig/shaders/gbuffers_terrain.fsh lite/shaders/gbuffers_terrain.fsh
--- lite_orig/shaders/gbuffers_terrain.fsh	2020-08-26 09:03:06.000000000 -0700
+++ lite/shaders/gbuffers_terrain.fsh	2020-12-28 13:54:20.224684970 -0800
@@ -21,6 +21,9 @@
 const int gaux4Format = R11F_G11F_B10F;	
 -----------------------------------------*/
 
+#if nMap >= 1
+#extension GL_ARB_shader_texture_lod : enable
+
 varying vec4 color;
 varying vec4 texcoord;
 varying vec4 normal;
@@ -41,8 +44,6 @@
 	return vec3( 0.25*c.r+0.5*c.g+0.25*c.b, 0.5*c.r-0.5*c.b +0.5, -0.25*c.r+0.5*c.g-0.25*c.b +0.5);
 }
 vec3 newnormal = normal.xyz;
-#if nMap >= 1
-#extension GL_ARB_shader_texture_lod : enable
 uniform sampler2D normals;
 varying float block;
 bool isblock = block > 0.0 || block < 0.0; //workaround for 1.16 bugs on block entities
```
~I haven't explored thoroughly, but it seemed like bumpmapping only worked in sunlight and not underground in torchlight.~

**Comment by Sildurs-shaders** [comment]
What's your gpu?

**Comment by plredmond** [comment]
I'm using an [old MacBookPro](https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.5-15-dual-graphics-mid-2015-retina-display-specs.html) with a discrete GPU "AMD Radeon R9 M370X" listed as "AMD VERDE" according to glxinfo.

Feel free to close this as "wontfix" if you don't think it's important or affecting other users. I've edited the shaders and with the patch above and mostly obtained a configuration that works for me at about 30fps.

**Comment by Sildurs-shaders** [comment]
Does this still happen on the latest version, v1.29?

**Comment by plredmond** [comment]
It's fixed on
* Minecraft 1.17.1
* OptiFine HD U G9
* Sildur's Vibrant shaders v1.29 Lite
* 
* Thank you

**Comment by Sildurs-shaders** [comment]
I suppose the other presets work aswell then and this can be closed.
