### ISSUE TITLE
Clicking Sildur's Enhanced Default v1.12 instantly crashes Minecraft

### ISSUE THREAD

**Issue by TBlazeWarriorT** [Sildurs-shaders/sildurs-shaders.github.io#126]
I tried using Sildur's Enhanced Default v1.12, but it just crashes my game very instantly with java.lang.NoSuchFieldError, can't figure out why. All other shaders work fine, using 1.12.2 with Forge and OptiFine, which falls within "supported MC versions 1.7.10 - 1.16.5". I'm using Windows and made sure I had downloaded the shaderpack correctly and in the right format.
The TL;DR seems to be that my optifine simply can't parse the shader at all and crashes minecraft.

`Description: Updating screen events

java.lang.NoSuchFieldError: field_191308_b
	at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
	at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
	at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1086)
	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:948)
	at net.optifine.shaders.Shaders.setShaderPack(Shaders.java:871)
	at net.optifine.shaders.gui.GuiSlotShaders.selectIndex(GuiSlotShaders.java:91)
	at net.optifine.shaders.gui.GuiSlotShaders.func_148144_a(GuiSlotShaders.java:81)
	at net.minecraft.client.gui.GuiSlot.func_178039_p(GuiSlot.java:323)
	at net.optifine.shaders.gui.GuiShaders.func_146274_d(GuiShaders.java:117)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by Sildurs-shaders** [comment]
Update optifine
