### ISSUE TITLE
Rain Drops OFF in v1.50 causes ShaderCompileException

### ISSUE THREAD

**Issue by JasonWeinzierl** [Sildurs-shaders/sildurs-shaders.github.io#260]
When I turn off Rain Drops under Sky & Lighting, shaders fail to load (Vibrant shaders, both Extreme-VL and Medium).  The following is logged in `latest.log`.

(The only other option I changed is Waves amplitude to 0.55)

```[15:55:34] [Render thread/INFO]: Profile: Custom (+2 options changed by user)
[15:55:34] [Render thread/INFO]: Using shaderpack: Sildur's+Vibrant+Shaders+v1.50+Extreme-VL.zip
[15:55:34] [Render thread/INFO]: Creating pipeline for dimension OVERWORLD
[15:55:34] [Render thread/WARN]: Shader compilation log for final.vsh: 0(47) : error C1503: undefined variable "eyeBrightnessSmooth"
0(52) : error C1503: undefined variable "rainStrength"

[15:55:34] [Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
net.coderbot.iris.gl.shader.ShaderCompileException: 0(47) : error C1503: undefined variable "eyeBrightnessSmooth"
0(52) : error C1503: undefined variable "rainStrength"

	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:46) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:25) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:98) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:43) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.createProgram(FinalPassRenderer.java:331) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.lambda$new$0(FinalPassRenderer.java:85) ~[iris-mc1.19.3-1.4.6.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.<init>(FinalPassRenderer.java:81) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:246) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:664) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:606) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:556) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$3(ShaderPackScreen.java:241) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:31) ~[client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:195) ~[iris-mc1.19.3-1.4.6.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:310) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1222) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[fabric-loader-0.14.12-1.19.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.12.jar:?]
```

This does not occur using shaders v1.41.

I am on Minecraft v1.19.3.  Mods installed: Iris 1.4.6; Sodium 0.4.6; No Chat Reports.

**Comment by Sildurs-shaders** [comment]
Will fix it in the next update or maybe ninja update it at some time, but for now you want to open final.vsh with a text editor and change the following:
```
#ifdef Rain_Drops
varying vec2 rainPos1;
varying vec2 rainPos2;
varying vec2 rainPos3;
varying vec2 rainPos4;
varying vec4 weights;
uniform ivec2 eyeBrightnessSmooth;
uniform float rainStrength;
uniform float frameTimeCounter;

vec2 noisepattern(vec2 pos) {
	return vec2(abs(fract(sin(dot(pos, vec2(83147.6995379f, 125370.887575f))))));
}
#endif
```
to
```
uniform ivec2 eyeBrightnessSmooth;
uniform float rainStrength;
#ifdef Rain_Drops
varying vec2 rainPos1;
varying vec2 rainPos2;
varying vec2 rainPos3;
varying vec2 rainPos4;
varying vec4 weights;
uniform float frameTimeCounter;

vec2 noisepattern(vec2 pos) {
	return vec2(abs(fract(sin(dot(pos, vec2(83147.6995379f, 125370.887575f))))));
}
#endif
```

**Comment by Sildurs-shaders** [comment]
Closed because of https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/290
