### ISSUE TITLE
Shader compilation fails for Sildur's Vibrant Extreme 1.50 on both OptiFine and Iris when Rain Drops (`Rain_Drops`) are disabled.

### ISSUE THREAD

**Issue by akemin-dayo** [Sildurs-shaders/sildurs-shaders.github.io#280]
Shader compilation fails for Sildur's Vibrant Extreme 1.50 on both OptiFine and Iris when Rain Drops (`Rain_Drops`) are disabled.

I have reproduced this issue with a completely fresh stock copy of Sildur's Vibrant Extreme 1.50 with no other changes made aside from disabling rain drops.

The issue appears to be caused by two undefined variables referenced somewhere — `eyeBrightnessSmooth` and `rainStrength`.

## OptiFine stack trace
```
[Render thread/ERROR]: [Shaders] Error compiling vertex shader: /shaders/final.vsh
[Render thread/INFO]: [Shaders] File: 1 = /shaders/shaders.settings
[Render thread/INFO]: [Shaders] Shader info log: /shaders/final.vsh
0(72) : error C1503: undefined variable "eyeBrightnessSmooth"
0(80) : error C1503: undefined variable "rainStrength"
[Render thread/ERROR]: [Shaders] Error linking program: 193 (final)
[Render thread/INFO]: [Shaders] Program info log: final
Vertex info
-----------
0(72) : error C1503: undefined variable "eyeBrightnessSmooth"
0(80) : error C1503: undefined variable "rainStrength"
(0) : error C2003: incompatible options for link
[Thread-18/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. <program> has not been linked, or is not a program object.)
java.lang.Exception: Stack trace
	at net.minecraft.class_1008.method_4224(class_1008.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.1.jar:?]
[Thread-18/INFO]: [CHAT] ˜eOpenGL Error˜f: 1282 (Invalid operation)
[Thread-18/ERROR]: OpenGL API ERROR: 1282 (GL_INVALID_OPERATION error generated. <program> object is not successfully linked, or is not a program object.)
java.lang.Exception: Stack trace
	at net.minecraft.class_1008.method_4224(class_1008.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:46) [lwjgl-opengl-3.3.1.jar:?]
[Render thread/ERROR]: [Shaders] OpenGL error: 1282 (Invalid operation), program: final, at: useProgram
[Render thread/INFO]: [CHAT] ˜eOpenGL Error˜f: 1282 (Invalid operation)
[Render thread/ERROR]: [Shaders] [Shaders] Error: Invalid program "final"
[Render thread/INFO]: [CHAT] [Shaders] Error: Invalid program "final"
```

## Iris stack trace
```
[Render thread/WARN]: Shader compilation log for final.vsh: 0(47) : error C1503: undefined variable "eyeBrightnessSmooth"
0(52) : error C1503: undefined variable "rainStrength"

[Render thread/ERROR]: Failed to create shader rendering pipeline, disabling shaders!
java.lang.RuntimeException: Shader compilation failed!
	at net.coderbot.iris.postprocess.FinalPassRenderer.createProgram(FinalPassRenderer.java:349) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.lambda$new$0(FinalPassRenderer.java:93) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.<init>(FinalPassRenderer.java:89) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:265) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:656) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.Iris.reload(Iris.java:598) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:543) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25419(ShaderPackScreen.java:504) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$1(ShaderPackScreen.java:225) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:120) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[client-intermediary.jar:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.method_25402(ShaderPackScreen.java:181) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:489) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.1.jar:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:build 7]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) [lwjgl-glfw-3.3.1.jar:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1208) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) [quilt-loader-0.17.11.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.11.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.11.jar:?]
Caused by: java.lang.RuntimeException: Failed to compile VERTEX shader for program final.vsh
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:100) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:43) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.createProgram(FinalPassRenderer.java:345) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	... 37 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
	at net.coderbot.iris.gl.shader.GlShader.createShader(GlShader.java:46) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.gl.shader.GlShader.<init>(GlShader.java:25) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.buildShader(ProgramBuilder.java:98) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.gl.program.ProgramBuilder.begin(ProgramBuilder.java:43) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	at net.coderbot.iris.postprocess.FinalPassRenderer.createProgram(FinalPassRenderer.java:345) ~[iris-mc1.19.2-1.19-1.5.2-ad3fdf68~akemi-gitCommitDate-20230207-111708+0900JST-gitBranch-1.19.1.jar:?]
	... 37 more
```

**Comment by downloadpizza** [comment]
I made a quick summary on how to fix this here: https://github.com/Sildurs-shaders/sildurs-shaders.github.io/issues/290
While sildur works his way through the issues you can fix it by hand, just unzip and edit.
