### ISSUE TITLE
Sildur's Enhanced Default shadows causes a crash in nether

### ISSUE THREAD

**Issue by RancerRex** [Sildurs-shaders/sildurs-shaders.github.io#343]
As the titles indicates, there is a crash that happens when shadows are enabled when entering the nether, it's an instantaneous crash.
I'm using Fabric 1.21 with the Iris mod, it might be a crash with iris itself, but with other shaders this crash does not happen.
Here is a snippet of the crash repport:
Description: Unexpected error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_284.method_35660()" because "shader.field_29470" is null
	at net.diebuddies.render.MainRenderer.setupModelViewMatrix(MainRenderer.java:441)
	at net.diebuddies.render.MainRenderer.render(MainRenderer.java:406)
	at net.diebuddies.render.MainRenderer.renderAll(MainRenderer.java:222)
	at net.minecraft.class_761.handler$dch000$physicsmod$renderMain(class_761.java:13687)
	at net.minecraft.class_761.method_3251(class_761.java:15753)
	at net.minecraft.class_761.invokeRenderSectionLayer(class_761.java)
	at net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:462)
	at net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1020)
	at net.minecraft.class_761.handler$bni000$iris$renderTerrainShadows(class_761.java:7782)
	at net.minecraft.class_761.method_22710(class_761.java:977)
	at net.minecraft.class_757.method_3188(class_757.java:1087)
	at net.minecraft.class_757.method_3192(class_757.java:850)
	at net.minecraft.class_310.method_1523(class_310.java:1285)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by RancerRex** [comment]
I found out that it also crashes in the end, althoght it's not an intantaneous crash, it only happened when I got close to the dragon.

**Comment by RancerRex** [comment]
I also found out, that it may have something to do with the physics mod, I disabled and the crash didn't happen immediately, but after I loaded a fortress it crashed. So I will keep this open, although it might've been because of the physics mod, disabling it did help, but it still crashed.

**Comment by therealstrizzi** [comment]
happening here as well. instant crash when entering the nether.
I'm not running the physics mod, so that can't be it.

**Comment by Fierce2005** [comment]
it's the same with these shaders

**Comment by BronsonCarder** [comment]
I'm getting this same crash, but I'm not using Sildur's, I'm using Hysteria Shaders.
It does mention the physics mod in the log, which I am also running. But the implication, to me, is that there is a third culprit. 

I'm running No Cubes and Distant Horizons, those seem like the biggest possibilities.

**Comment by Sildurs-shaders** [comment]
This was probably a mod issue, I can't replicate it.
