### ISSUE TITLE
Sildur's Enhanced Default crash in the nether and the end

### ISSUE THREAD

**Issue by Fierce2005** [Sildurs-shaders/sildurs-shaders.github.io#350]
at knot//net.minecraft.class_761.method_3251(class_761.java:17748)
at knot//net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:462)
at knot//net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1020)
at knot//net.minecraft.class_761.handler$dbe000$iris$renderTerrainShadows(class_761.java:10288)
at knot//net.minecraft.class_761.method_22710(class_761.java:1014)
at knot//net.minecraft.class_757.method_3188(class_757.java:1098)
at knot//net.minecraft.class_757.method_3192(class_757.java:866)
at knot//net.minecraft.class_310.method_1523(class_310.java:1327)
at knot//net.minecraft.class_310.method_1514(class_310.java:888)
at knot//net.minecraft.client.main.Main.main(Main.java:265)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at knot//net.irisshaders.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.vivecraft$createAllPipelinesShadersSodiumProcessing(IrisChunkProgramOverrides.java:590)
at knot//net.irisshaders.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.redirect$hcc000$vivecraft$createAllPipelinesShadersSodium_0_6(IrisChunkProgramOverrides.java:546)
... 20 more
Caused by: java.lang.RuntimeException: Shader compilation failed, see log for details
at knot//me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
at knot//net.irisshaders.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createFragmentShader(IrisChunkProgramOverrides.java:161)
at knot//net.irisshaders.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShader(IrisChunkProgramOverrides.java:198)
at knot//net.irisshaders.iris.compat.sodium.impl.shader_overrides.IrisChunkProgramOverrides.createShaders(IrisChunkProgramOverrides.java:309)
... 26 more

**Comment by Fierce2005** [comment]
forget it, I'm on version 1.20.4, the problem was solved when I installed the shader version 1.16, I hadn't read the description of the shader versions before
