### ISSUE TITLE
Crash when loading High Vibrant Shaders, using 1.12.2 forge

### ISSUE THREAD

**Issue by supermattdab0ss** [Sildurs-shaders/sildurs-shaders.github.io#99]
When I attempt to load the High Vibrant shaders v1.281 using optifine loaded via forge, I experience a crash and am unable to use the shaders. I am using OptiFine 1.12.2 U F5 loaded via Forge #2847 rather than installed to a profile. After investigating further, this happens with 1.62, and any versions later but none prior. It also happens with the latest version of 1.12.2 forge, #2854. I have also confirmed this happens with both lite and extreme volumetric lighting versions as well. Crash report below:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/3/20 11:53 AM
Description: Updating screen events

java.lang.NoSuchFieldError: field_191308_b
	at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
	at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
	at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1086)
	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:948)
	at net.optifine.shaders.Shaders.setShaderPack(Shaders.java:871)
	at net.optifine.shaders.gui.GuiSlotShaders.selectIndex(GuiSlotShaders.java:91)
	at net.optifine.shaders.gui.GuiSlotShaders.func_148144_a(GuiSlotShaders.java:81)
	at net.minecraft.client.gui.GuiSlot.func_178039_p(GuiSlot.java:348)
	at net.optifine.shaders.gui.GuiShaders.func_146274_d(GuiShaders.java:117)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
	at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
	at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
	at net.optifine.shaders.Shaders.loadShaderPackProperties(Shaders.java:1086)
	at net.optifine.shaders.Shaders.loadShaderPack(Shaders.java:948)
	at net.optifine.shaders.Shaders.setShaderPack(Shaders.java:871)
	at net.optifine.shaders.gui.GuiSlotShaders.selectIndex(GuiSlotShaders.java:91)
	at net.optifine.shaders.gui.GuiSlotShaders.func_148144_a(GuiSlotShaders.java:81)
	at net.minecraft.client.gui.GuiSlot.func_178039_p(GuiSlot.java:348)
	at net.optifine.shaders.gui.GuiShaders.func_146274_d(GuiShaders.java:117)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.optifine.shaders.gui.GuiShaders
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 479103744 bytes (456 MB) / 965738496 bytes (921 MB) up to 12117344256 bytes (11556 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms130m -Xmx13000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                                  | Signature |
	|:------ |:--------- |:------------ |:--------------------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                           | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                           | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847-universal.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847-universal.jar | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.48' Renderer: 'GeForce GTX 1080/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.48, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 1700 Eight-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs Vibrant Shaders v1.281 High.zip
	OpenGlVersion: 4.6.0 NVIDIA 451.48
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by supermattdab0ss** [comment]
Switching to Optifine 1.12.2 HD U F6 pre1 solved this issue. Going to leave it open in case there is something that can be done without switching to a more obscure and less supported version of Optifine.

**Comment by Sildurs-shaders** [comment]
Optifine issue, as you said it's fixed in the preview build. Up to the optifine author to make it a normal build.
